spring.application.name=asis-app-be

spring.datasource.url=jdbc:postgresql://ep-patient-hall-aid8wyy3-pooler.c-4.us-east-1.aws.neon.tech/propenuy-asis?user=neondb_owner&password=npg_OkeD0q6FgBRy&sslmode=require&channelBinding=require
# spring.datasource.username=namuser
# spring.datasource.password=passwordnya

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect